export const imageData = {
  "hero": [
    { 
      "src": "/images/hero/0.jpg", 
      "hint": "education campus",
      "pill": "Preparing Innovators for Tomorrow",
      "title": "Education Beyond Theory",
      "subtitle": "Modern campus facilities designed for future-ready learning."
    },
    { 
      "src": "/images/hero/1.jpg", 
      "hint": "students classroom",
      "pill": "Excellence in Academics",
      "title": "Learn from the Best",
      "subtitle": "Our experienced faculty is dedicated to your success."
    },
    { 
      "src": "/images/hero/2.jpg", 
      "hint": "science laboratory",
      "pill": "Hands-On Learning",
      "title": "Innovation in Practice",
      "subtitle": "State-of-the-art labs for practical, real-world experience."
    },
    { 
      "src": "/images/hero/3.jpg", 
      "hint": "students collaborating",
      "pill": "Collaborative Community",
      "title": "Grow and Succeed Together",
      "subtitle": "A vibrant campus life that fosters teamwork and leadership."
    },
    { 
      "src": "/images/hero/4.jpg", 
      "hint": "library students",
      "pill": "Your Future Starts Here",
      "title": "A World of Knowledge",
      "subtitle": "Explore our extensive library and digital resources."
    }
  ],
  "staff": {
    "dr_laxman_basnet": { "src": "/images/staffs/dr._laxman_basnet.jpg", "hint": "male portrait" },
    "santosh_pandey": { "src": "/images/staffs/santosh_pandey.jpg", "hint": "male portrait" },
    "bhagwat_dev_bhatt": { "src": "/images/staffs/bhagwat_dev_bhatt.jpg", "hint": "male portrait" },
    "dipendra_joshi": { "src": "/images/staffs/dipendra_joshi.jpg", "hint": "male portrait" },
    "bed_prakash_bhatt": { "src": "/images/staffs/bed_prakash_bhatt.jpg", "hint": "male portrait" },
    "karan_singh_mahara": { "src": "/images/staffs/karan_singh_mahara.jpg", "hint": "male portrait" },
    "bhupendra_chand": { "src": "/images/staffs/bhupendra_chand.jpg", "hint": "male portrait" },
    "bhuwan_chandra_bogati": { "src": "/images/staffs/bhuwan_chandra_bogati.jpg", "hint": "male portrait" },
    "pushpa_raj_bhatt": { "src": "/images/staffs/pushpa_raj_bhatt.jpg", "hint": "male portrait" },
    "narendra_awasthi": { "src": "/images/staffs/narendra_awasthi.jpg", "hint": "male portrait" },
    "suraj_pant": { "src": "https://picsum.photos/seed/suraj/400/400", "hint": "male portrait" },
    "shiv_raj_bohara": { "src": "/images/staffs/shiv_raj_bohara.jpg", "hint": "male portrait" },
    "meen_bahadur_khadka": { "src": "/images/staffs/meen_bahadur_khadka.jpg", "hint": "male portrait" },
    "sudarshan_prashad_bhatt": { "src": "/images/staffs/sudarshan_prashad_bhatt.jpg", "hint": "male portrait" },
    "gyandeb_bhatt": { "src": "/images/staffs/gyandeb_bhatt.jpg", "hint": "male portrait" },
    "pushpa_joshi": { "src": "https://picsum.photos/seed/pushpajoshi/400/400", "hint": "female portrait" },
    "govind_giri": { "src": "/images/staffs/govind_giri.jpg", "hint": "male portrait" },
    "birendra_bahadur_chand": { "src": "/images/staffs/birendra_bahadur_chand.jpg", "hint": "male portrait" },
    "rajesh_datt_bhatt": { "src": "/images/staffs/rajesh_datt_bhatt.jpg", "hint": "male portrait" },
    "rituraj_bhatt": { "src": "/images/staffs/rituraj_bhatt.jpg", "hint": "male portrait" },
    "dev_raj_paneru": { "src": "https://picsum.photos/seed/devraj/400/400", "hint": "male portrait" },
    "jeewan_thapa": { "src": "/images/staffs/jeewan_thapa.jpg", "hint": "male portrait" },
    "dev_singh_bhandari": { "src": "https://picsum.photos/seed/devsingh/400/400", "hint": "male portrait" },
    "kokila_pant": { "src": "/images/staffs/kokila_pant.jpg", "hint": "female portrait" },
    "saraswati_bist": { "src": "/images/staffs/saraswati_bist.jpg", "hint": "female portrait" },
    "basanti_chand": { "src": "https://picsum.photos/seed/basanti/400/400", "hint": "female portrait" },
    "dashrath_chand": { "src": "https://picsum.photos/seed/dashrath/400/400", "hint": "male portrait" },
    "puran_rana": { "src": "https://picsum.photos/seed/puran/400/400", "hint": "male portrait" }
  },
  "gallery": [
  { "src": "/images/gallery/1.jpg", "hint": "students rangoli", "title": "Cultural Celebration", "category": "Events" },
  { "src": "/images/gallery/2.jpg", "hint": "teacher outdoor lesson", "title": "Nature Study Session", "category": "Tours" },
  { "src": "/images/gallery/3.jpg", "hint": "students exam classroom", "title": "Academic Assessment", "category": "Campus" },
  { "src": "/images/gallery/4.jpg", "hint": "group student portrait", "title": "Management Students Group", "category": "Campus" },
  { "src": "/images/gallery/5.jpg", "hint": "eye checkup clinic", "title": "Health & Vision Screening", "category": "Events" },
  { "src": "/images/gallery/6.jpg", "hint": "kids sitting circle", "title": "Preschool Creative Activity", "category": "Campus" },
  { "src": "/images/gallery/7.jpg", "hint": "potted plant message", "title": "Green Earth Initiative", "category": "Projects" },
  { "src": "/images/gallery/8.jpg", "hint": "school building exterior", "title": "SARC Foundation Building", "category": "Campus" },
  { "src": "/images/gallery/9.jpg", "hint": "students forest field", "title": "Educational Field Trip", "category": "Tours" },
  { "src": "/images/gallery/10.jpg", "hint": "science exhibition models", "title": "Math & Science Fair", "category": "Projects" },
  { "src": "/images/gallery/11.jpg", "hint": "kids graduation ceremony", "title": "Kindergarten Graduation", "category": "Events" },
  { "src": "/images/gallery/12.jpg", "hint": "students morning assembly", "title": "Morning PT Drill", "category": "Campus" },
  { "src": "/images/gallery/13.jpg", "hint": "student group discussion", "title": "Collaborative Learning Session", "category": "Projects" },
  { "src": "/images/gallery/14.jpg", "hint": "large group student photo", "title": "Classroom Group Portrait", "category": "Campus" },
  { "src": "/images/gallery/15.jpg", "hint": "temple visit field trip", "title": "Cultural Heritage Tour", "category": "Tours" },
  { "src": "/images/gallery/16.jpg", "hint": "medical simulation lab", "title": "Health Science Demonstration", "category": "Labs" },
  { "src": "/images/gallery/17.jpg", "hint": "robotics project building", "title": "Robotics & STEM Workshop", "category": "Labs" },
  { "src": "/images/gallery/18.jpg", "hint": "student made vehicle", "title": "Innovative Engineering Project", "category": "Projects" },
  { "src": "/images/gallery/19.jpg", "hint": "astronomy telescope observation", "title": "Space Science Observation", "category": "Labs" },
  { "src": "/images/gallery/20.jpg", "hint": "botany nature walk", "title": "Environmental Field Study", "category": "Tours" },
  { "src": "/images/gallery/21.jpg", "hint": "students in chemistry lab", "title": "Chemistry Practical Session", "category": "Labs" },
  { "src": "/images/gallery/22.jpg", "hint": "annual day stage celebration", "title": "SARC Annual Day Celebration", "category": "Events" },
  { "src": "/images/gallery/23.jpg", "hint": "students using microscopes", "title": "Microscope Observation Practice", "category": "Labs" },
  { "src": "/images/gallery/24.jpg", "hint": "engineering project display", "title": "Student-Built Vehicle Exhibition", "category": "Projects" },
  { "src": "/images/gallery/25.jpg", "hint": "students in conference room", "title": "Interactive Seminar Session", "category": "Campus" },
  { "src": "/images/gallery/26.jpg", "hint": "innovative engineering model", "title": "Mechanical Engineering Project", "category": "Projects" },
  { "src": "/images/gallery/27.jpg", "hint": "girls at swimming pool", "title": "School Swimming Activity", "category": "Campus" },
  { "src": "/images/gallery/28.jpg", "hint": "students in computer lab", "title": "Digital Literacy Class", "category": "Labs" },
  { "src": "/images/gallery/29.jpg", "hint": "school transportation fleet", "title": "SARC School Transportation", "category": "Campus" },
  { "src": "/images/gallery/30.jpg", "hint": "advanced ICT computer lab", "title": "Technology & AI Learning", "category": "Labs" },
  { "src": "/images/gallery/31.jpg", "hint": "students robotics project", "title": "Robotics & Innovation Lab", "category": "Projects" },
  { "src": "/images/gallery/32.jpg", "hint": "students cleaning campus", "title": "Social Service Program", "category": "Events" },
  { "src": "/images/gallery/33.jpg", "hint": "prize distribution ceremony", "title": "Sports Award Ceremony", "category": "Sports" },
  { "src": "/images/gallery/34.jpg", "hint": "students playing football", "title": "Futsal Tournament", "category": "Sports" },
  { "src": "/images/gallery/35.jpg", "hint": "medical checkup student", "title": "Student Health Care", "category": "Campus" },
  { "src": "/images/gallery/36.jpg", "hint": "student giving speech", "title": "Speech Competition", "category": "Events" }
  ]
}
