export const imageData = {
  "hero": [
    { 
      "src": "/images/hero/0.jpg", 
      "hint": "education campus",
      "pill": "Preparing Innovators for Tomorrow",
      "title": "Education Beyond Theory",
      "subtitle": "Modern campus facilities designed for future-ready learning."
    },
    { 
      "src": "/images/hero/1.jpg", 
      "hint": "students classroom",
      "pill": "Excellence in Academics",
      "title": "Learn from the Best",
      "subtitle": "Our experienced faculty is dedicated to your success."
    },
    { 
      "src": "/images/hero/2.jpg", 
      "hint": "science laboratory",
      "pill": "Hands-On Learning",
      "title": "Innovation in Practice",
      "subtitle": "State-of-the-art labs for practical, real-world experience."
    },
    { 
      "src": "/images/hero/3.jpg", 
      "hint": "students collaborating",
      "pill": "Collaborative Community",
      "title": "Grow and Succeed Together",
      "subtitle": "A vibrant campus life that fosters teamwork and leadership."
    },
    { 
      "src": "/images/hero/4.jpg", 
      "hint": "library students",
      "pill": "Your Future Starts Here",
      "title": "A World of Knowledge",
      "subtitle": "Explore our extensive library and digital resources."
    }
  ],
  "staff": {
    "dr_laxman_basnet": { "src": "/images/staffs/dr._laxman_basnet.jpg", "hint": "male portrait" },
    "santosh_pandey": { "src": "/images/staffs/santosh_pandey.jpg", "hint": "male portrait" },
    "bhagwat_dev_bhatt": { "src": "/images/staffs/bhagwat_dev_bhatt.jpg", "hint": "male portrait" },
    "dipendra_joshi": { "src": "/images/staffs/dipendra_joshi.jpg", "hint": "male portrait" },
    "bed_prakash_bhatt": { "src": "/images/staffs/bed_prakash_bhatt.jpg", "hint": "male portrait" },
    "karan_singh_mahara": { "src": "/images/staffs/karan_singh_mahara.jpg", "hint": "male portrait" },
    "bhupendra_chand": { "src": "/images/staffs/bhupendra_chand.jpg", "hint": "male portrait" },
    "bhuwan_chandra_bogati": { "src": "/images/staffs/bhuwan_chandra_bogati.jpg", "hint": "male portrait" },
    "pushpa_raj_bhatt": { "src": "/images/staffs/pushpa_raj_bhatt.jpg", "hint": "male portrait" },
    "narendra_awasthi": { "src": "/images/staffs/narendra_awasthi.jpg", "hint": "male portrait" },
    "suraj_pant": { "src": "https://picsum.photos/seed/suraj/400/400", "hint": "male portrait" },
    "shiv_raj_bohara": { "src": "/images/staffs/shiv_raj_bohara.jpg", "hint": "male portrait" },
    "meen_bahadur_khadka": { "src": "/images/staffs/meen_bahadur_khadka.jpg", "hint": "male portrait" },
    "sudarshan_prashad_bhatt": { "src": "/images/staffs/sudarshan_prashad_bhatt.jpg", "hint": "male portrait" },
    "gyandeb_bhatt": { "src": "/images/staffs/gyandeb_bhatt.jpg", "hint": "male portrait" },
    "pushpa_joshi": { "src": "https://picsum.photos/seed/pushpajoshi/400/400", "hint": "female portrait" },
    "govind_giri": { "src": "/images/staffs/govind_giri.jpg", "hint": "male portrait" },
    "birendra_bahadur_chand": { "src": "/images/staffs/birendra_bahadur_chand.jpg", "hint": "male portrait" },
    "rajesh_datt_bhatt": { "src": "/images/staffs/rajesh_datt_bhatt.jpg", "hint": "male portrait" },
    "rituraj_bhatt": { "src": "/images/staffs/rituraj_bhatt.jpg", "hint": "male portrait" },
    "dev_raj_paneru": { "src": "https://picsum.photos/seed/devraj/400/400", "hint": "male portrait" },
    "jeewan_thapa": { "src": "/images/staffs/jeewan_thapa.jpg", "hint": "male portrait" },
    "dev_singh_bhandari": { "src": "https://picsum.photos/seed/devsingh/400/400", "hint": "male portrait" },
    "kokila_pant": { "src": "/images/staffs/kokila_pant.jpg", "hint": "female portrait" },
    "saraswati_bist": { "src": "/images/staffs/saraswati_bist.jpg", "hint": "female portrait" },
    "basanti_chand": { "src": "https://picsum.photos/seed/basanti/400/400", "hint": "female portrait" },
    "dashrath_chand": { "src": "https://picsum.photos/seed/dashrath/400/400", "hint": "male portrait" },
    "puran_rana": { "src": "https://picsum.photos/seed/puran/400/400", "hint": "male portrait" }
  },
  "gallery": [
    { "src": "/images/gallery/1.jpg", "hint": "teacher student", "title": "Student Welcome", "category": "Cultural" },
    { "src": "/images/gallery/2.jpg", "hint": "events celebration", "title": "Campus Walk", "category": "Projects" },
    { "src": "/images/gallery/3.jpg", "hint": "academics classroom", "title": "Health Center", "category": "Campus" },
    { "src": "/images/gallery/4.jpg", "hint": "sports game", "title": "Computer Lab", "category": "Campus" },
    { "src": "/images/gallery/5.jpg", "hint": "students studying", "title": "Science Laboratory", "category": "Campus" },
    { "src": "/images/gallery/6.jpg", "hint": "college event", "title": "Lab Equipment", "category": "Campus" },
    { "src": "/images/gallery/7.jpg", "hint": "science lab", "title": "Science Project Exhibition", "category": "Events" },
    { "src": "/images/gallery/8.jpg", "hint": "basketball game", "title": "Science Experiment", "category": "Campus" },
    { "src": "/images/gallery/9.jpg", "hint": "campus building", "title": "International Tour", "category": "Tours" },
    { "src": "/images/gallery/10.jpg", "hint": "graduation ceremony", "title": "Practical Tour", "category": "Projects" },
    { "src": "/images/gallery/11.jpg", "hint": "library books", "title": "Temple Visit", "category": "Events" },
    { "src": "/images/gallery/12.jpg", "hint": "football match", "title": "Annual Function", "category": "Campus" },
    { "src": "/images/gallery/13.jpg", "hint": "student discussion", "title": "Science Fest - Bike Show", "category": "Projects" },
    { "src": "/images/gallery/14.jpg", "hint": "cultural event", "title": "Science Fest - Car Show", "category": "Campus" },
    { "src": "/images/gallery/15.jpg", "hint": "lecture hall", "title": "Science Fest - CAE Show", "category": "Tours" },
    { "src": "/images/gallery/16.jpg", "hint": "running track", "title": "International Conference", "category": "Labs" },
    { "src": "/images/gallery/17.jpg", "hint": "friends chatting", "title": "Sports Prize Distribution", "category": "Projects" },
    { "src": "/images/gallery/18.jpg", "hint": "music festival", "title": "Sports & Football", "category": "Projects" },
    { "src": "/images/gallery/19.jpg", "hint": "studying outdoors", "title": "Extra Curricular Activities", "category": "Tours" },
    { "src": "/images/gallery/20.jpg", "hint": "volleyball game", "title": "Social Work", "category": "Tours" },
    { "src": "/images/gallery/21.jpg", "hint": "campus nature", "title": "Chemistry Experiment", "category": "Labs" },
    { "src": "/images/gallery/22.jpg", "hint": "award ceremony", "title": "Microscope Practice I", "category": "Events" },
    { "src": "/images/gallery/23.jpg", "hint": "group project", "title": "Microscope Practice II", "category": "Labs" },
    { "src": "/images/gallery/24.jpg", "hint": "cricket match", "title": "Chemistry Demonstration", "category": "Projects" },
    { "src": "/images/gallery/25.jpg", "hint": "college building", "title": "Group Study Session", "category": "Events" },
    { "src": "/images/gallery/26.jpg", "hint": "annual day", "title": "Annual Day Celebration", "category": "Projects" },
    { "src": "/images/gallery/27.jpg", "hint": "chemistry lab", "title": "Physics Lab Experiment", "category": "Campus" },
    { "src": "/images/gallery/28.jpg", "hint": "table tennis", "title": "Table Tennis Match", "category": "Sports" },
    { "src": "/images/gallery/29.jpg", "hint": "college corridor", "title": "College Corridor", "category": "Campus" },
    { "src": "/images/gallery/30.jpg", "hint": "farewell party", "title": "Farewell Ceremony", "category": "Labs" },
    { "src": "/images/gallery/31.jpg", "hint": "computer lab", "title": "Robotics Project", "category": "Projects" },
    { "src": "/images/gallery/32.jpg", "hint": "badminton court", "title": "Badminton Tournament", "category": "Events" },
    { "src": "/images/gallery/33.jpg", "hint": "student life", "title": "Cultural Dance", "category": "Sports" },
    { "src": "/images/gallery/34.jpg", "hint": "student life", "title": "Debate Competition", "category": "Sports" },
    { "src": "/images/gallery/35.jpg", "hint": "student life", "title": "Art Workshop", "category": "Campus" },
    { "src": "/images/gallery/36.jpg", "hint": "student life", "title": "Field Trip", "category": "Events" }
  ]
}
